AllCops:
  Exclude:
    - Rakefile
    - test/*.rb
    - lib/sdk/models/shared/*.rb
    - lib/sdk/models/operations/*.rb
    - lib/sdk/*.rb
  TargetRubyVersion: "3.0"
Metrics:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
