# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Structure
  module Shared
    class Account < Structure::Utils::FieldAugmented
      extend T::Sig

            # List of the users in the account
      field :account_users, T::Array[String]      # Timestamp of the account creation date
      field :created_at, String      # The id of the account
      field :id, Float      # The name of the account
      field :name, String      # The id of the account owner
      field :owner_id, Float      # If the account is personal or belonging to another account
      field :personal, T::Boolean      # Timestamp of the last account update date
      field :updated_at, String

      sig { params(account_users: T::Array[String], created_at: String, id: Float, name: String, owner_id: Float, personal: T::Boolean, updated_at: String).void }
      def initialize(account_users: nil, created_at: nil, id: nil, name: nil, owner_id: nil, personal: nil, updated_at: nil)
        @account_users = account_users
        @created_at = created_at
        @id = id
        @name = name
        @owner_id = owner_id
        @personal = personal
        @updated_at = updated_at
      end
    end
  end
end
