# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Structure
  module Shared# 2 - returns the company
    class Company < Structure::Utils::FieldAugmented
      extend T::Sig

            # The company's description
      field :about, String      # Affiliated companies to the company
      field :affiliated, T::Array[String]      # The size of the company
      field :company_size, String      # The country's country code
      field :country_code, String      # A sample of the company's employees. See the employees endpoint for the full list.
      field :employees, T::Array[String]      # The number of company employees on LinkedIn
      field :employees_in_linkedin, Float      # The number of company followers on LinkedIn
      field :followers, Float      # The year the company was founded
      field :founded, Float      # The funding status of the company
      field :funding, String      # The country's headquarters
      field :headquarters, String      # The key for looking up the company
      field :id, Float      # The company's industries
      field :industries, String      # The company's investors
      field :investors, String      # Sample of company's Jobs. See the jobs endpoint for the full list.
      field :jobs, T::Array[String]      # The company's LinkedIn ID
      field :lid, String      # The company's locations
      field :locations, T::Array[String]      # URL to the company's logo
      field :logo, String      # The company's name
      field :name, String      # The type of organization
      field :organization_type, String      # The company's profiles
      field :profiles, T::Array[String]      # The comapny's headquarters region
      field :region, String      # Similar companies to this company
      field :similar, T::Array[String]      # The company's slogan
      field :slogan, String      # The company's specialities
      field :specialities, String      # The company's sphere of products
      field :sphere, String      # The type of company (public, private, etc.)
      field :type, String      # The company's linkedIn URL
      field :url, String      # The company's website
      field :website, String

      sig { params(about: String, affiliated: T::Array[String], company_size: String, country_code: String, employees: T::Array[String], employees_in_linkedin: Float, followers: Float, founded: Float, funding: String, headquarters: String, id: Float, industries: String, investors: String, jobs: T::Array[String], lid: String, locations: T::Array[String], logo: String, name: String, organization_type: String, profiles: T::Array[String], region: String, similar: T::Array[String], slogan: String, specialities: String, sphere: String, type: String, url: String, website: String).void }
      def initialize(about: nil, affiliated: nil, company_size: nil, country_code: nil, employees: nil, employees_in_linkedin: nil, followers: nil, founded: nil, funding: nil, headquarters: nil, id: nil, industries: nil, investors: nil, jobs: nil, lid: nil, locations: nil, logo: nil, name: nil, organization_type: nil, profiles: nil, region: nil, similar: nil, slogan: nil, specialities: nil, sphere: nil, type: nil, url: nil, website: nil)
        @about = about
        @affiliated = affiliated
        @company_size = company_size
        @country_code = country_code
        @employees = employees
        @employees_in_linkedin = employees_in_linkedin
        @followers = followers
        @founded = founded
        @funding = funding
        @headquarters = headquarters
        @id = id
        @industries = industries
        @investors = investors
        @jobs = jobs
        @lid = lid
        @locations = locations
        @logo = logo
        @name = name
        @organization_type = organization_type
        @profiles = profiles
        @region = region
        @similar = similar
        @slogan = slogan
        @specialities = specialities
        @sphere = sphere
        @type = type
        @url = url
        @website = website
      end
    end
  end
end
