# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Structure
  module Shared
    class Security < Structure::Utils::FieldAugmented
      extend T::Sig

      
      field :bearer_auth, String, { 'security': { 'scheme': true, 'type': 'http', 'sub_type': 'bearer', 'field_name': 'Authorization' } }

      sig { params(bearer_auth: String).void }
      def initialize(bearer_auth: nil)
        @bearer_auth = bearer_auth
      end
    end
  end
end
