# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'
require 'faraday'

module Structure
  module Operations
    class LoginApplicationJSON < Structure::Utils::FieldAugmented
      extend T::Sig

            # The email of the user
      field :email, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('email') } }      # The password of the user
      field :password, String, { 'format_json': { 'letter_case': OpenApiSDK::Utils.field_name('password') } }

      sig { params(email: String, password: String).void }
      def initialize(email: nil, password: nil)
        @email = email
        @password = password
      end
    end

    class LoginResponse < Structure::Utils::FieldAugmented
      extend T::Sig

      
      field :content_type, String
      field :status_code, Integer
      field :body, T.nilable(String)
      field :raw_response, T.nilable(Faraday::Response)

      sig { params(content_type: String, status_code: Integer, body: T.nilable(String), raw_response: T.nilable(Faraday::Response)).void }
      def initialize(content_type: nil, status_code: nil, body: nil, raw_response: nil)
        @content_type = content_type
        @status_code = status_code
        @body = body
        @raw_response = raw_response
      end
    end
  end
end
